Repository geoadmin/service-shortlink, pull requests merged in 2021-11, with the labels that each got.

#21 BGDIINF_SB-2021: remove `/shortlinks`
  .env.default
  .env.testing
  Makefile
  Pipfile
  Pipfile.lock
  README.md
  app/__init__.py
  app/helpers/checks.py
  app/helpers/urls.py
  app/middleware.py
  app/models/dynamo_db.py
  app/routes.py
  app/settings.py
  docker-compose.yml
  openapi.yaml
  service_config.py
  tests/unit_tests/__init__.py
  tests/unit_tests/base.py
  tests/unit_tests/test_helpers.py
  tests/unit_tests/test_routes.py
  wsgi.py
Labels: feature

#24 Deleted obsolete variable
  app/routes.py
Labels: skip-release-note

#27 BGDIINF_SB-2027: Cache-Control, CORS and charset
  .env.default
  Makefile
  README.md
  app/__init__.py
  app/helpers/__init__.py
  app/helpers/response_generation.py
  app/helpers/utils.py
  app/routes.py
  app/settings.py
  service_launcher.py
  tests/unit_tests/base.py
  tests/unit_tests/test_routes.py
  tests/unittest.cfg
  wsgi.py
Labels: feature

#25 #major New Release v2.0.0
  .dockerignore
  .env.default
  .env.testing
  .github/workflows/main.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/semver.yml
  .isort.cfg
  Makefile
  Pipfile
  Pipfile.lock
  README.md
  app/__init__.py
  app/helpers/__init__.py
  app/helpers/checks.py
  app/helpers/response_generation.py
  app/helpers/urls.py
  app/helpers/utils.py
  app/middleware.py
  app/models/dynamo_db.py
  app/routes.py
  app/settings.py
  buildspec.yml
  docker-compose.yml
  getPythonCmd.sh
  logging-cfg-dev.yaml
  logging-cfg-prod.yaml
  openapi.yaml
  service_config.py
  service_launcher.py
  tests/unit_tests/__init__.py
  tests/unit_tests/base.py
  tests/unit_tests/test_helpers.py
  tests/unit_tests/test_routes.py
  tests/unittest.cfg
  wsgi.py
Labels: new-release

#29 BGDIINF_SB-2027: Added Access-Control-Allow-Headers in responses
  app/__init__.py
  tests/unit_tests/base.py
Labels: bug

#30 BGDIINF_SB-2043: Changed default `GET /<shortlink>` to redirect and don't validate origin for redirect
  app/__init__.py
  app/helpers/route.py
  app/helpers/utils.py
  app/routes.py
  tests/unit_tests/test_routes.py
Labels: bug

#32 Don't add CORS to /checker
  app/__init__.py
  app/helpers/utils.py
Labels: feature

#33 BGDIINF_SB-2046: Corrected the generic function get_registered_method()
  .env.default
  app/__init__.py
  app/helpers/utils.py
Labels: bug

#34 Release v2.1.0
  .env.default
  app/__init__.py
  app/helpers/route.py
  app/helpers/utils.py
  app/routes.py
  tests/unit_tests/base.py
  tests/unit_tests/test_routes.py
Labels: new-release

#35 BGDIINF_SB-2049: Added service version to checker answer
  app/routes.py
  tests/unit_tests/test_routes.py
Labels: feature

#36 Consolidate PR workflows
  .github/workflows/pr-auto-semver.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/semver.yml
Labels: skip-release-note

#37 Renamed the workflow templates
  .github/workflows/pr-auto-semver.yml
  .github/workflows/semver.yml
Labels: skip-release-note
